# Generated by Django 6.0.4 on 2026-05-11 21:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('designer', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, null=True, unique=True)),
                ('primary_image_url', models.URLField(blank=True)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list)),
                ('body', models.TextField(blank=True)),
                ('vendors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('keycaps', 'Keycaps'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=20)),
                ('thread_type', models.CharField(blank=True, choices=[('instock', 'In Stock'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'thread_type'], name='threads_thr_status_e9ed9e_idx'), models.Index(fields=['item_type'], name='threads_thr_item_ty_3c3263_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
            ],
            options={
                'unique_together': {('user', 'thread')},
            },
        ),
    ]
