# Generated by Django 6.0.4 on 2026-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='post_date',
            field=models.DateField(),
        ),
    ]
