# Generated by Django 6.0.4 on 2026-05-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_alter_savedthread_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='designer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
