# Generated by Django 6.0.4 on 2026-05-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='item_type',
            field=models.CharField(choices=[('keyboard', 'Keyboard'), ('keycaps', 'Keycaps'), ('other', 'Other'), ('unknown', 'Unknown')], default='keyboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(blank=True, choices=[('instock', 'In Stock'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20, null=True),
        ),
    ]
